import os
env = Environment(ENV = os.environ)

env.Append(CXXFLAGS=["-std=c++11","-Wall","-O3"])
#env.Append(CXXFLAGS=["-std=c++11","-Wall","-g"])
env.Append(CPPPATH=["../eigen3/"])
env.Append(LIBS=["glut","GL","X11"])
env.Append(LINKFLAGS=[])

env.Program("fluid_sims",["main.cpp","parse.cpp","sims.cpp"])

